(in-package #:rpi-dashboard.sensors)

(defvar *ds18b20-sensor-basedir* #P"/sys/bus/w1/devices/")

(defun read-DS18B20-temperature ()
  (let ((sensor-file (cl-fad:merge-pathnames-as-file (find-if (lambda (p)
                                                                (search "28" (namestring p)))
                                                              (cl-fad:list-directory "/sys/bus/w1/devices/" :follow-symlinks t))
                                                     #P"w1_slave")))
    (with-open-file (stream sensor-file)
      (let ((control-line (read-line stream))
            (temperature-line (read-line stream)))
        (when (search "YES" control-line)
          (parse-integer (subseq temperature-line (+ 2 (search "t=" temperature-line)))
                         :junk-allowed t))))))
